### ISSUE TITLE
CSRF error when deploy with caddy.

### ISSUE THREAD

**Issue by mr-ant** [rafalp/Misago#1038]
`CSRF Failed: CSRF token missing or incorrect.`
Do I need to add extra configuration to caddy？
Thanks.

**Comment by rafalp** [comment]
Hey @mr-ant!

> Do I need to add extra configuration to caddy？

"CSRF Failed" error means that your browser failed to include proper `csrftoken` cookie with request sent to your server. This may be caused by wrong cookies configuration, attempting to run multiple django apps under single domain, or browser plugin not accepting the cookies.

I don't know what "caddy" is. :(

**Comment by mr-ant** [comment]
Hey @rafalp 
Thanks for your kind help.now is worked perfect！
