### ISSUE TITLE
Explore moving the docs to Docusaurus and hosting them on gitpages.

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1060]

**Comment by mdanish0771** [comment]
I got hosting on gitpages for my [stroller blog](https://sethoxreviews.com/best-convertible-stroller/) and I am satisfied. hosting is perfect and i really like its smoothness. what you say?

**Comment by sureshHARDIYA** [comment]
Hi @rafalp, I have bee using Docusaurus for long and must say am pretty happy with it. The best part of using it was, It does not require much programming skills. So, most of my team members, even my support guys were able to follow the website and create beautiful docs for external clients. So, I 100% support moving the docs to Docusaurus.

**Comment by justanotherteammate** [comment]
@rafalp, this issue is marked as 'welcome issue' for new people. It's TODO or still *decision needed*?

Hi @sureshHARDIYA ! Happy to see you. Please explain me, cause I don't see milestones claimed.
Do you started to move that or just claim that it's good decision? I don't know if somebody will work on it.

I am too low in project to get more vital issues and have no exp with Docusaurus, but if you have some rules of thumb or pages with nice conf tricks easing usage, please refer it here! I love to read that.

Best regards.

**Comment by rafalp** [comment]
Hey @justanotherteammate 

> @rafalp, this issue is marked as 'welcome issue' for new people. It's TODO or still decision needed?

I don't know where you see "welcome issue" - this task is pretty much a to do for me, because I would like this page to live under main domain and also contain marketing claims for Misago ;)

But yup, I've also built few pages with Docusaurus, so I am convinced to it, just waiting for 2.0 to land. 👍

**Comment by justanotherteammate** [comment]
Hmm... I made mistake. One of GitHub's feature shows some open issues to people on project page.

Thank you for answer :)

**Comment by mattbryanswan** [comment]
FYI - I think this page is what he was referring:

https://github.com/rafalp/Misago/contribute

It lists three 'docs' issues as good first issues.

**Comment by rafalp** [comment]
Closing as dupe of #236

I have a plan for Misago future site to be Docusaurus 2 powered and combine both docs and marketing. But I'll get to it after I'm over with more important work, and there's prolly years of that.
