### ISSUE TITLE
Installation in an existing Django project

### ISSUE THREAD

**Issue by de-don** [rafalp/Misago#1178]
Can I install this forum as a section of an existing project for example for the path "/forum"?

**Comment by rafalp** [comment]
Hey!

As rule of thumb Misago should be ran as stand-alone application on its own instance, and use technology-agnostic approach for integration (JWT for user accounts and JSON API for data).

This is because Misago is complex project with large number of features, assumptions and dependencies. It would take considerable development effort to integrate it with existing Django project, and in turn would give little actual gain and introduce great maintenance burden on your project:

- if Misago moves to Django 2.2 or Python 3.7 and some of dependencies specific to your project will turn out to be incompatible with it, you will need to update your project on your own or lag behind with Misago changes.
- if Misago moves to ASGI for asynchronous connections and GraphQL subscriptions, but you will have to update your deployment on your own.
- you will have to do maintenance of Celery deployment: setup Redis, make sure it keys don't clash with whatever your app may be doing.
- if you'll want to customize User model, you'll have to maintain custom DB migrations and keep track of Misago changes in DB. This one is going to be absolute killer because Misago implements boatload of social features around User model, not to mention protections for GDPR compliance.

All of the above is non-issue with separate deployment, because Docker takes care of it all for you.

I would also like to add that this approach is de-facto industry standard for software integrations. You'll find it in, say, Discourse that is Ruby on Rails application, and yet doesn't support use as Rails module ("engine"). Same goes for E-comm platforms, CRM's and project management solutions. You want to be technology agnostic so more software can integrate with you, and in turn, your project is useful to more people.

**Comment by de-don** [comment]
Thanks for the answer!

**Comment by rafalp** [comment]
There's also #415 issue for using JWT to integrate with existing sites user systems.
