### ISSUE TITLE
Add schema.org attributes to make html understandable for Crawlers.

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#125]
* [x] WebSite with url

**Threads list**

* [x] Categories list
* [x] Threads list
* [x] Pagination

**Thread**

* [x] Breadcrumbs
* [x] Posts list
* [x] Pagination

**Users list**

* [x] Tabs
* [x] Users cards
* [x] Pagination
* [x] Activity ranking

**Comment by ioanb7** [comment]
I would enjoy working on this as I need it for a future website.

Is there anyway you can release 0.6.1 and then have incremental tools for each subsequent version, 0.6.2, 0.6.3?

I have to develop a few things inside Misago, but I either have to do them in 0.5 where the code is not as superb as this one, or I have to wait for 0.6.

What do you think? I am sure I am not the only one in this position.

**Comment by rafalp** [comment]
Sorry, I am not going to release 0.6 before milestone. I understand that you have use for it *right now*, but there's always somebody out there who's in situation like this. Thats the reality of open source development.

You can either move on to look for other software to use for your purspose, or bite it and maintain your own fork, keeping an eye on what's happening on master, merging up features and maintaining migrations specific for your fork.

**Comment by ioanb7** [comment]
I understand, thanks.

**Comment by rafalp** [comment]
To add something I've missed yesterday: 0.6's while feature incomplete, already implements more features than basic PHP forum software like PunBB/FluxBB does. Its core package is here, meaning your users may discuss, and there are all moderation tools in place required for moderating discussion and keeping members in check. I simply want more than that in MVP.

**Comment by ioanb7** [comment]
When my friend looked up a few forum options and stumbled upon yours, we were both like "holy, this is genius". The code written for misago 0.5 is okey, but the one for 0.6 is superb.

I don't care if there are missing features, it's not perfect, and pages crash from time to time. I just want something to run.

I would want to add the following:
* LDAP login
* JSON service to return players online, most recent ones, admins online, comments for a post, a service to easily create a new thread at a request from another website, etc. useful features as part of a bigger portal.
* HTML5 microdata - essential for indexing, i hope.

On a forum I saw you've changed your mind about what javascript framework library to use, have you settled on this one?

My biggest fear is that I will make these and then something switches and I am stuck with a version that is not going to be compatible with what you are working on in the feature. For example, a massive reconstruction of the database structure, having to manually import data from the past, losing some, and not knowing where I started and where I have to go. This is mostly because I find Misago quite vast.

Do you have a plan, milestones, modules that you want to do a complete do-over and it's best I would deactivate them for now?

I am really interested in this project and I don't mind having only the basic modules for now. As long as I know I won't have to lose data.

Also, one more question: what's the date you plan on releasing 0.6 alpha 1?

I am going to look through the apps you've wrote and how the code is layed out, albeit I am not a frequent user of unit tests.

**Comment by rafalp** [comment]
> On a forum I saw you've changed your mind about what javascript framework library to use, have you settled on this one?

Yup. There'll be plenty of cleaning up in frontend, because its quite messy (after all it was my first larger run at React.js, and I've got few things wrong), but React, React-Router and Redux is here to stay.

Only really big change on frontend that I'm planning is move to Bootstrap 4 from Bootstrap 3 when beta finally arrives and I'm done with other stuff for Alpha, but this is half-year away from the looks of it, and by the time you'll likely be on Alpha that will be receiving updates.


> For example, a massive reconstruction of the database structure

Nah. Ther's one change to Misago's DB before Alpha 1 happens that I would call disruptive: the move from serialized dicts to `JsonField` in few tables. But, to be honest, I may be dramatising here. ;)


> Also, one more question: what's the date you plan on releasing 0.6 alpha 1?

Hopefully I'll wrap it all up by the January 2017.

**Comment by ioanb7** [comment]
That sounds great!

I will go ahead and start working on and with Misago 0.6 then. 

> Nah. Ther's one change to Misago's DB before Alpha 1 happens that I would call disruptive: the move from serialized dicts to JsonField in few tables. But, to be honest, I may be dramatising here. ;)

Is there anyway you could prioritise this in the next 2-3 weeks, or at least let me know what you want to do, so I can make it?

Regards,
Ioan

**Comment by rafalp** [comment]
Nope. I'll get to it when I'll get to it. I do open source on my own terms. Helps keep me engaged and don't burn out. ;)

**Comment by ioanb7** [comment]
i hoped we can help each other. ok mate.
