### ISSUE TITLE
Does Misago has server side rendering?

### ISSUE THREAD

**Issue by vaibhavmule** [rafalp/Misago#581]

**Comment by rafalp** [comment]
No because Misago isn't SPA. React-Router is used for implementing features like Tabs/Pagination within components, but if you click user's avatar in thread, you will still get whole-page reload.

React components are used mostly for interactivity, ergo: forms, lists of items with actions, dynamic timestamps, tabs.

**Comment by rafalp** [comment]
To elaborate further, React components are mounted within Django returned markup in client, with every component having non-JS fallback (that look mostly the same, but lack interactivity features like buttons) and forms having "enable JS to do this!" messages in their place.
