### ISSUE TITLE
why PostgreSQL only?

### ISSUE THREAD

**Issue by kinsney** [rafalp/Misago#623]
Can I use mysql instead?

**Comment by rafalp** [comment]
Is there any specific reason you need MySQL instead?

Decision comes from simple reasons: I'm developing and optimizing against PostgreSQL. I'm using some features that are specific to it like piartial indexes, some complex queries involving subqueries in Misago, and JSONFields or fulltext search facilities that are supported by Django's ORM:

https://docs.djangoproject.com/es/1.10/ref/contrib/postgres/

**Comment by ioanb7** [comment]
I wanted to ask the same question.
Is quite silly I had to install postgresql just to run misago. The first time I saw the config in the config file I was like "hmm, that's interesting."
I've heard a few good things about postgresql, a few years ago. I can't remember what they were, nor I had to. I've used mysql for 5-6 years now without ever needing postgresql.
If I will have to use postgresql for misago, I am going to have to spend some hours learning it. I tried giving permission to my IP outside vagrant and it's very different from mysql.
I am just running Varnish in front of Misago, anyway. So the benefit that people get from using one rational db over the other is kind of pointless. We've moved to NoSQL and complex caching systems.

Great work Rafal, I love Misago, but if you could make it work in MySQL, all the better.

Regards,
Ioan

**Comment by kinsney** [comment]
Thanks for your reply
Actually I got nothing specific, just curious about 
What if I integrate Misago into another existing Django project using MySQL as its App?
With JSONField, maybe I will use plugins like jsonfield instead.

Anyway, Misago is a great project, thanks for all your work.

**Comment by rafalp** [comment]
> So the benefit that people get from using one rational db over the other is kind of pointless.

It's not. You are still comparing database A that has certain features with database B that hasn't:

- partial indexes
- viable and quick per-row locks in transactions
- multiple indexes per single query support (this is biggie because different engines create different execution plans for same queries and datasets, and fast query on one engine may drop to terrible hard drive buffer in the other)
- fulltext search with results rating and dictionary-based tokenization of strings

Those quirks are overcomeable. You may introduce dependency on ElasticSearch or Sphinx for forum search. You may design your features and site structure (and by result database) around MySQL's query planner instead of PostgreSQL's one.

But there are two things to keep on mind:

This is open source project, and there's always more to do than there's time to. You'll eventually bias towards one RMDBS becoming primary and other one being aftertought. There's plenty of PHP software out there that support both MySQL and PostgreSQL, but because the former is so much more popular in PHP world, those solutions ultimately bias towards it and struggle with the performance on the latter, [some eventually dropping it](https://invisionpower.com/forums/topic/400144-ipb-4-support-postgresql/).

This leads us to second point which is "just like how PHP implementations are biased towards MySQL, Django implementations are biased towards PostgreSQL". If you look at ISP's, PAAS'es or SAAS'es targeting Django, you'll noticed that PostgreSQL is pretty much standard.

Speaking form my own experience, I've seen MySQL as data store in Django only happens in two scenarios:

- people with past history in PHP coming to Django not seeing reason for going to PostgreSQL, (I've did this, I also see this a lot in junior devs)
- existing infrastructure is already on MySQL (propably due to past PHP implementations) and moving to other RDBMS is unacceptable

**Comment by ioanb7** [comment]
I understand.

Thanks Rafał.
