### ISSUE TITLE
User status on user lists gets vertical scroll

### ISSUE THREAD

**Issue by armata** [rafalp/Misago#695]
There's a scroll that probably shouldn't be there in the global users list.

Link: https://misago-project.org/users/active-posters/

![](https://i.gyazo.com/9a198012d60771cbe881457aab051e5d.png)

**Comment by rafalp** [comment]
Not a checkbox. ;) Its scroll for user status being too large for its container. ;)

**Comment by armata** [comment]
Obviously not a checbox :D I guess it was just my ADD doing its thing 👎 

Issue decription edited, I'll try to fix this one!

**Comment by rafalp** [comment]
Can you confirm if scolls still appear on this list?

**Comment by armata** [comment]
It does not appear anymore but the user group name is a bit higher than the rest of the text.

Picture (see "Devs & Contributors"): https://i.gyazo.com/2faf8d77ff1bf8676df2e77ec69c1d0f.png

**Comment by rafalp** [comment]
Ok, how about now?

**Comment by armata** [comment]
Same -- in Chrome, Edge and IE.

**Comment by rafalp** [comment]
I'll let that than hang then, seeing how original issue is fixed and this looks perfect at my device, getting this pixel perfect is going to be hairy.

**Comment by armata** [comment]
Alright :)

**Comment by rafalp** [comment]
Getitng this pixel-perfect indeed turned out to be hairy, but I've worked it out.

Apparently MacOs's was using Helvetice Nueue and Windows was using Arial. And subtle differences between those two made it impossible to get those to show in single line. I've made it so both of systems default to their native `Sans-Serif` font, which apparently is San Fran at Sierra and Arial at Win 7.

**Comment by armata** [comment]
Thanks! Looks awesome now :)
