### ISSUE TITLE
Posts appear as hidden after posting JSON to API url

### ISSUE THREAD

**Issue by ioanb7** [rafalp/Misago#697]
Hi Rafal,

I think there is something going wrong when making a new thread.
Here is my JS code that works almost fine:

```
$.post('/api/threads/', {title: "asdasdas", category: 3, post: "dasdasd", attachments: [], close: false, hide: false, pin: 0,
      csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value}, function(data){
        var url = data.url; //"/t/asdasdas/14/
          window.location.replace(url);
        

      }, "json");
```

The post appear, but it shows as: http://imgur.com/a/3pUZf

If, however, I create a link normally - pressing Start Thread and typing everything normally, it works.

**Comment by rafalp** [comment]
Looking at Misago's code, hide is actually sent as either 1 or 0, not true/false. Could you try that instead?

**Comment by ioanb7** [comment]
I just tried that, it doesn't work unfortunately.

The error is easily replicable, just post the code into a Console window and make sure the category id (in my case 3) is valid.

I copied the code that it sends through by watching the Networking tab in Chrome Developer Tools. So it should work..

**Comment by rafalp** [comment]
Allright, back home, I've got minute to check this out:

Request made via `misago/services/ajax`:

```
<type 'bool'>
True
```

Request made via your method:

```
<type 'unicode'>
u'false'
```

Looking at jQuery's docs, the parameter you are passing the `"json"` as value forces jquery to interpret server's response as JSON. This means data you are sending to backend is read as form data by Django's Rest Framework, instead of JSON data. This results in "false" being evaluated to non-empty string which is `True`.

**Comment by ioanb7** [comment]
Thanks, that did it.
